---
title: "Untitled"
author: "Le Luo"
date: "2024-11-13"
output: html_document
---

```{r}
library(prophet)
library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)


df <- read_xlsx("/Users/jio/Desktop/EMRTS intern/draft/NJ enrollment draft.xlsx")
head(df)
colnames(df)
```


```{r}
df$`Report Date` <- as.Date(df$`Report Date`)
df_prophet <- data.frame(ds = df$`Report Date`, y = df$`Total Medicaid Enrollment`)
df_prophet <- na.omit(df_prophet)
model <- prophet(df_prophet)

future <- make_future_dataframe(model, periods = 120, freq = 'month')
forecast <- predict(model, future)
forecast_plot <- plot(model, forecast) + ggtitle("Medicaid Enrollment Forecast in New Jersey")
regression_line <- data.frame(ds = forecast$ds, trend = forecast$trend)
forecast_plot + geom_line(data = regression_line, aes(x = ds, y = trend))
```
```{r}
trend_forecast <- data.frame(Date = forecast$ds, Trend_Forecast = forecast$trend)
trend_forecast$Year <- format(trend_forecast$Date, "%Y")
yearly_trend_forecast <- aggregate(Trend_Forecast ~ Year, data = trend_forecast, FUN = mean)
yearly_trend_forecast$Trend_Forecast <- format(as.numeric(yearly_trend_forecast$Trend_Forecast), big.mark = ",")
colnames(yearly_trend_forecast) <- c("Year", "Forecast Yearly Enrollment According to Trend")
yearly_trend_forecast
```

```{r}
forecast$Year <- format(forecast$ds, "%Y")
yearly_forecast <- aggregate(yhat ~ Year, data = forecast, FUN = mean)
colnames(yearly_forecast) <- c("Year", "Forecast Yearly Enrollment with Prophet")
yearly_forecast$`Forecast Yearly Enrollment with Prophet` <- format(as.numeric(yearly_forecast$`Forecast Yearly Enrollment with Prophet`), big.mark = ",")
yearly_forecast
```
