---
title: "Medicaid Enrollment & Expenditure Forecast Project"
author: "Le Luo"
date: "2024-09-16"
output: pdf_document
---

```{r}
install.packages("prophet")
install.packages("tidyverse")
install.packages("readxl")
install.packages("dplyr")

library(prophet)
library(tidyverse)
library(readr)
library(readxl)
library(dplyr)

```

```{r}
df <- read_xlsx("/Users/jio/Desktop/EMRTS intern/enrollment data.xlsx")
head(df)
```
```{r}
# I'll focus on data of New Jersey, filter the data
nj_data <- df %>%
  filter(`State Name` == "New Jersey") %>%
  select(`Report Date`, `Total Medicaid Enrollment`)

nj_data$`Report Date` <- as.Date(nj_data$`Report Date`, format="%Y-%m-%d")
nj_data <- nj_data %>%
  rename(ds = `Report Date`, y = `Total Medicaid Enrollment`)
```

```{r}
model <- prophet(yearly.seasonality = TRUE, monthly.seasonality = FALSE, weekly.seasonality = FALSE, daily.seasonality = FALSE)
model <- fit.prophet(model, nj_data)
future <- make_future_dataframe(model, periods = 10, freq = 'year')
forecast <- predict(model, future)
```

```{r}
plot(model, forecast)
prophet_plot_components(model, forecast)
tail(forecast[c('ds', 'yhat', 'yhat_lower', 'yhat_upper')],n=10)
```

