---
title: "Medicaid expenditure forecast"
author: "Le Luo"
date: "2024-09-20"
output: pdf_document
---

```{r}
install.packages('prophet')
library(prophet)
install.packages("readxl")
library(readxl)

df <- read_xlsx("/Users/jio/Desktop/EMRTS intern/expenditure data/expenditure combine.xlsx")
head(df)
colnames(df)
```

```{r}
head(df$Time)
head(df$TotalMedicaidExpenditures)

df$Time <- as.numeric(df$Time)

df_clean <- data.frame(ds = as.Date(paste0(df$Time, "-01-01"), format="%Y-%m-%d"), y = df$TotalMedicaidExpenditures)
df_clean <- na.omit(df_clean)

model <- prophet(df_clean)

future <- make_future_dataframe(model, periods=10, freq = 'year')

forecast <- predict(model, future)
plot(model, forecast)
prophet_plot_components(model, forecast)

forecast_result <- forecast[c('ds', 'yhat', 'yhat_lower', 'yhat_upper')]
colnames(forecast_result) <- c("Date", "Predicted_Value", "Lower_Bound", "Upper_Bound")
forecast_result$Predicted_Value <- format(forecast_result$Predicted_Value, big.mark = ",", scientific = FALSE)
forecast_result$Lower_Bound <- format(forecast_result$Lower_Bound, big.mark = ",", scientific = FALSE)
forecast_result$Upper_Bound <- format(forecast_result$Upper_Bound, big.mark = ",", scientific = FALSE)

forecast_result$Predicted_Value <- as.numeric(gsub(",", "", forecast_result$Predicted_Value))
forecast_result$Percentage_Increase <- c(NA, diff(forecast_result$Predicted_Value) / 
                                                        head(forecast_result$Predicted_Value, -1) * 100)
tail(forecast_result, n=10)
```
